apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis
  namespace: auth
spec:
  selector:
    matchLabels:
      app: profile
  replicas: 1
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: genesis
        image: nginx
        ports:
        - containerPort: 80